/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package chamsockh.Voucher;

import BLL.VoucherBLL;
import chamsockh.DichVu.frmDichVu;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MINH HOANG
 */
public class frmVoucher extends javax.swing.JInternalFrame {

    VoucherBLL _bll = new VoucherBLL();
    Vector data = new Vector();
    Vector header = new Vector();
    /**
     * Creates new form frmVoucher
     */
    public frmVoucher() {
        initComponents();
        initTable();
        ResultSet rs = _bll.getAllVoucher();
        try {
            while(rs.next()){
                Vector<String> info = new Vector<String>();
                info.add(rs.getString("MV"));
                info.add(rs.getString("TenV"));
                info.add(rs.getString("GiamGia"));
                data.add(info);
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmVoucher.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void initTable(){
        header.add("Mã voucher");
        header.add("Tên voucher");
        header.add("Giảm giá");

        tblVoucher.setModel(new DefaultTableModel(data, header));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtMaVoucher = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTenVoucher = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVoucher = new javax.swing.JTable();
        btnTimKiem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtGiamGia = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Voucher");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel1.setText("Mã voucher");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));
        getContentPane().add(txtMaVoucher, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 148, -1));

        jLabel3.setText("Tên voucher");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));
        getContentPane().add(txtTenVoucher, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 148, -1));

        tblVoucher.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã voucher", "Tên voucher", "Giảm giá"
            }
        ));
        tblVoucher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVoucherMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblVoucher);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 500, -1));

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        getContentPane().add(btnTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        getContentPane().add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        jLabel4.setText("Giảm giá");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));
        getContentPane().add(txtGiamGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 150, -1));

        btnThem.setText("Thêm");
        getContentPane().add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        btnLuu.setText("Lưu");
        getContentPane().add(btnLuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblVoucherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVoucherMouseClicked
//        displayDetail(((JTable)evt.getSource()).getSelectedRow());
    }//GEN-LAST:event_tblVoucherMouseClicked

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        String madv = txtMaVoucher.getText();
        String tendv = txtTenVoucher.getText();

//        if(madv.isEmpty() && tendv.isEmpty()){
//            loadAllData();
//        } else {
//            if(madv.isEmpty() == false){
//                loadDataByMaDV(madv);
//            } else {
//                loadDataByTenDV(tendv);
//            }
//        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
//        String madv = txtMaVoucher.getText();
//        if(madv.isEmpty()){
//            System.out.println("Vui lòng nhập mã dịch vụ để xóa");
//        } else {
//            try{
//                int kq = dvBll.delete(madv);
//                JOptionPane.showMessageDialog(this, "Xóa dịch vụ thành công");
//                loadAllData();
//            } catch (Exception e){
//                JOptionPane.showMessageDialog(this, "Lỗi không thể xóa dịch vụ");
//            }
//        }
    }//GEN-LAST:event_btnXoaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVoucher;
    private javax.swing.JTextField txtGiamGia;
    private javax.swing.JTextField txtMaVoucher;
    private javax.swing.JTextField txtTenVoucher;
    // End of variables declaration//GEN-END:variables
}
