/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package chamsockh.LienHe;

/**
 *
 * @author MINH HOANG
 */
public class frmLienHe extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmLienHe
     */
    public frmLienHe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtMaLienHe = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnTimKiem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        cboTinhTrangLH = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVoucher = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblDichVu = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Liên hệ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel1.setText("Mã liên hệ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));
        getContentPane().add(txtMaLienHe, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 150, -1));

        jLabel3.setText("Thời gian liên hệ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        getContentPane().add(btnTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        getContentPane().add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        jLabel4.setText("Tình trạng");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        getContentPane().add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, -1));

        jFormattedTextField1.setToolTipText("__/__/____");
        getContentPane().add(jFormattedTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 120, -1));

        cboTinhTrangLH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "------------------", "Thành công", "Không thành công", " ", " " }));
        getContentPane().add(cboTinhTrangLH, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 150, -1));

        tblVoucher.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã voucher", "Tên voucher", "Giảm giá"
            }
        ));
        tblVoucher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVoucherMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblVoucher);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 450, 240));

        tblDichVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã dịch vụ", "Tên dịch vụ", "Mô tả", "Giá"
            }
        ));
        tblDichVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDichVuMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblDichVu);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, -1, 240));

        jLabel5.setText("DANH SÁCH VOUCHER LIÊN HỆ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        jLabel6.setText("DANH SÁCH DỊCH VỤ LIÊN HỆ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
//        String maVoucher = txtMaVoucher.getText();
//        String tenVoucher = txtTenVoucher.getText();
//
//        if(maVoucher.isEmpty() && tenVoucher.isEmpty()){
//            loadAllData();
//        } else {
//            if(maVoucher.isEmpty() == false){
//                loadDataByMaVoucher(maVoucher);
//            } else {
//                loadDataByTenVoucher(tenVoucher);
//            }
//        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
//        String maVoucher = txtMaVoucher.getText();
//        if(maVoucher.isEmpty()){
//            System.out.println("Vui lòng nhập mã dịch vụ để xóa");
//        } else {
//            int sl = _bll.getSLVoucherTheoMa(maVoucher);
//            if(sl == 0){
//                JOptionPane.showMessageDialog(this, "Không tồn tại mã voucher để xóa");
//            } else {
//                try{
//                    _bll.delete(maVoucher);
//                    JOptionPane.showMessageDialog(this, "Xóa voucher thành công");
//                    loadAllData();
//                } catch (Exception e){
//                    JOptionPane.showMessageDialog(this, "Lỗi không thể xóa voucher");
//                }
//            }
//        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
//        String maVoucher = txtMaVoucher.getText();
//        String tenVoucher = txtTenVoucher.getText();
//        var giamGia = Double.valueOf("0");
//        //String lienhe = ((ComboBoxItem)cboLienHe.getSelectedItem()).getKeyString();
//
//        if(maVoucher.isEmpty() || tenVoucher.isEmpty() || txtGiamGia.getText().isEmpty()){
//            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin để thêm voucher");
//            return;
//        }
//
//        try{
//            giamGia = Double.valueOf(txtGiamGia.getText());
//        } catch (Exception e){
//            JOptionPane.showMessageDialog(this, "Giảm giá phải thuộc [0,1]");
//            return;
//        }
//
//        if(giamGia < 0 || giamGia > 1){
//            JOptionPane.showMessageDialog(this, "Giảm giá phải thuộc [0,1]");
//            return;
//        }
//        try{
//            int sl = _bll.getSLVoucherTheoMa(maVoucher);
//            if(sl == 0){
//                _bll.insertNew(maVoucher, tenVoucher, giamGia);
//                JOptionPane.showMessageDialog(this, "Thêm voucher thành công");
//                loadAllData();
//            } else if(sl > 0) {
//                JOptionPane.showMessageDialog(this, "Lỗi trùng khóa mã voucher");
//            }
//        } catch (Exception e){
//            JOptionPane.showMessageDialog(this, "Lỗi không thể thêm mới dịch vụ");
//        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
//        String maVoucher = txtMaVoucher.getText();
//        String tenVoucher = txtTenVoucher.getText();
//        var giamGia = Double.valueOf("0");
//        //String lienhe = ((ComboBoxItem)cboLienHe.getSelectedItem()).getKeyString();
//
//        if(maVoucher.isEmpty() || tenVoucher.isEmpty() || txtGiamGia.getText().isEmpty()){
//            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin để sửa voucher");
//            return;
//        }
//
//        try{
//            giamGia = Double.valueOf(txtGiamGia.getText());
//        } catch (Exception e){
//            JOptionPane.showMessageDialog(this, "Giảm giá phải thuộc [0,1]");
//            return;
//        }
//
//        if(giamGia < 0 || giamGia > 1){
//            JOptionPane.showMessageDialog(this, "Giảm giá phải thuộc [0,1]");
//            return;
//        }
//        try{
//            int sl = _bll.getSLVoucherTheoMa(maVoucher);
//            if(sl == 0){
//                JOptionPane.showMessageDialog(this, "Không tồn tại voucher có mã " + maVoucher);
//            } else {
//                _bll.update(maVoucher, tenVoucher, giamGia);
//                loadAllData();
//                JOptionPane.showMessageDialog(this, "Sửa voucher thành công");
//            }
//        } catch (Exception e){
//            JOptionPane.showMessageDialog(this, "Lỗi không thể thêm mới dịch vụ");
//        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void tblVoucherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVoucherMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblVoucherMouseClicked

    private void tblDichVuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDichVuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblDichVuMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboTinhTrangLH;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblDichVu;
    private javax.swing.JTable tblVoucher;
    private javax.swing.JTextField txtMaLienHe;
    // End of variables declaration//GEN-END:variables
}
