/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package chamsockh.LienHe;

/**
 *
 * @author MINH HOANG
 */
public class frmThucHienLH extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmThucHienLH
     */
    public frmThucHienLH() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtMaLienHe = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVoucherAdded = new javax.swing.JTable();
        btnTimKiem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        cboTinhTrangLH = new javax.swing.JComboBox<>();
        btnToListDichVu = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVoucher = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDichVuAdded = new javax.swing.JTable();
        btnToListVoucher1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblDichVu = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Liên hệ");

        jLabel1.setText("Mã liên hệ");

        jLabel3.setText("Thời gian liên hệ");

        tblVoucherAdded.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã voucher", "Tên voucher", "Giảm giá"
            }
        ));
        tblVoucherAdded.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVoucherAddedMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblVoucherAdded);

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jLabel4.setText("Tình trạng");

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        jFormattedTextField1.setToolTipText("__/__/____");

        cboTinhTrangLH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "------------------", "Thành công", "Không thành công", " ", " " }));

        btnToListDichVu.setText(">>");

        tblVoucher.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã voucher", "Tên voucher", "Giảm giá"
            }
        ));
        tblVoucher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVoucherMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblVoucher);

        tblDichVuAdded.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã dịch vụ", "Tên dịch vụ", "Mô tả", "Giá"
            }
        ));
        tblDichVuAdded.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDichVuAddedMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblDichVuAdded);

        btnToListVoucher1.setText(">>");

        tblDichVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã dịch vụ", "Tên dịch vụ", "Mô tả", "Giá"
            }
        ));
        tblDichVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDichVuMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblDichVu);

        jLabel5.setText("DANH SÁCH VOUCHER LIÊN HỆ");

        jLabel6.setText("DANH SÁCH DỊCH VỤ LIÊN HỆ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1330, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel2))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(830, 830, 830)
                            .addComponent(jLabel5))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel1)
                                    .addGap(15, 15, 15)
                                    .addComponent(txtMaLienHe, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel3)
                                    .addGap(13, 13, 13)
                                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel4)
                                    .addGap(16, 16, 16)
                                    .addComponent(cboTinhTrangLH, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(150, 150, 150)
                                    .addComponent(btnTimKiem))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnThem)
                                    .addGap(8, 8, 8)
                                    .addComponent(btnXoa)
                                    .addGap(8, 8, 8)
                                    .addComponent(btnSua)))
                            .addGap(38, 38, 38)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(btnToListVoucher1)
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(830, 830, 830)
                            .addComponent(jLabel6))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(270, 270, 270)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnToListDichVu)
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 10, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(10, 10, 10)
                    .addComponent(jLabel5)
                    .addGap(4, 4, 4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(txtMaLienHe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(8, 8, 8)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(8, 8, 8)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(cboTinhTrangLH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(8, 8, 8)
                            .addComponent(btnTimKiem)
                            .addGap(27, 27, 27)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnThem)
                                .addComponent(btnXoa)
                                .addComponent(btnSua)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(100, 100, 100)
                            .addComponent(btnToListVoucher1))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addComponent(jLabel6)
                    .addGap(4, 4, 4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(110, 110, 110)
                            .addComponent(btnToListDichVu))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 10, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblVoucherAddedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVoucherAddedMouseClicked
        //        displayDetail(((JTable)evt.getSource()).getSelectedRow());
    }//GEN-LAST:event_tblVoucherAddedMouseClicked

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        //        String maVoucher = txtMaVoucher.getText();
        //        String tenVoucher = txtTenVoucher.getText();
        //
        //        if(maVoucher.isEmpty() && tenVoucher.isEmpty()){
            //            loadAllData();
            //        } else {
            //            if(maVoucher.isEmpty() == false){
                //                loadDataByMaVoucher(maVoucher);
                //            } else {
                //                loadDataByTenVoucher(tenVoucher);
                //            }
            //        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        //        String maVoucher = txtMaVoucher.getText();
        //        if(maVoucher.isEmpty()){
            //            System.out.println("Vui lòng nhập mã dịch vụ để xóa");
            //        } else {
            //            int sl = _bll.getSLVoucherTheoMa(maVoucher);
            //            if(sl == 0){
                //                JOptionPane.showMessageDialog(this, "Không tồn tại mã voucher để xóa");
                //            } else {
                //                try{
                    //                    _bll.delete(maVoucher);
                    //                    JOptionPane.showMessageDialog(this, "Xóa voucher thành công");
                    //                    loadAllData();
                    //                } catch (Exception e){
                    //                    JOptionPane.showMessageDialog(this, "Lỗi không thể xóa voucher");
                    //                }
                //            }
            //        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        //        String maVoucher = txtMaVoucher.getText();
        //        String tenVoucher = txtTenVoucher.getText();
        //        var giamGia = Double.valueOf("0");
        //        //String lienhe = ((ComboBoxItem)cboLienHe.getSelectedItem()).getKeyString();
        //
        //        if(maVoucher.isEmpty() || tenVoucher.isEmpty() || txtGiamGia.getText().isEmpty()){
            //            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin để thêm voucher");
            //            return;
            //        }
        //
        //        try{
            //            giamGia = Double.valueOf(txtGiamGia.getText());
            //        } catch (Exception e){
            //            JOptionPane.showMessageDialog(this, "Giảm giá phải thuộc [0,1]");
            //            return;
            //        }
        //
        //        if(giamGia < 0 || giamGia > 1){
            //            JOptionPane.showMessageDialog(this, "Giảm giá phải thuộc [0,1]");
            //            return;
            //        }
        //        try{
            //            int sl = _bll.getSLVoucherTheoMa(maVoucher);
            //            if(sl == 0){
                //                _bll.insertNew(maVoucher, tenVoucher, giamGia);
                //                JOptionPane.showMessageDialog(this, "Thêm voucher thành công");
                //                loadAllData();
                //            } else if(sl > 0) {
                //                JOptionPane.showMessageDialog(this, "Lỗi trùng khóa mã voucher");
                //            }
            //        } catch (Exception e){
            //            JOptionPane.showMessageDialog(this, "Lỗi không thể thêm mới dịch vụ");
            //        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        //        String maVoucher = txtMaVoucher.getText();
        //        String tenVoucher = txtTenVoucher.getText();
        //        var giamGia = Double.valueOf("0");
        //        //String lienhe = ((ComboBoxItem)cboLienHe.getSelectedItem()).getKeyString();
        //
        //        if(maVoucher.isEmpty() || tenVoucher.isEmpty() || txtGiamGia.getText().isEmpty()){
            //            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin để sửa voucher");
            //            return;
            //        }
        //
        //        try{
            //            giamGia = Double.valueOf(txtGiamGia.getText());
            //        } catch (Exception e){
            //            JOptionPane.showMessageDialog(this, "Giảm giá phải thuộc [0,1]");
            //            return;
            //        }
        //
        //        if(giamGia < 0 || giamGia > 1){
            //            JOptionPane.showMessageDialog(this, "Giảm giá phải thuộc [0,1]");
            //            return;
            //        }
        //        try{
            //            int sl = _bll.getSLVoucherTheoMa(maVoucher);
            //            if(sl == 0){
                //                JOptionPane.showMessageDialog(this, "Không tồn tại voucher có mã " + maVoucher);
                //            } else {
                //                _bll.update(maVoucher, tenVoucher, giamGia);
                //                loadAllData();
                //                JOptionPane.showMessageDialog(this, "Sửa voucher thành công");
                //            }
            //        } catch (Exception e){
            //            JOptionPane.showMessageDialog(this, "Lỗi không thể thêm mới dịch vụ");
            //        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void tblVoucherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVoucherMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblVoucherMouseClicked

    private void tblDichVuAddedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDichVuAddedMouseClicked
        //        displayDetail(((JTable)evt.getSource()).getSelectedRow());
    }//GEN-LAST:event_tblDichVuAddedMouseClicked

    private void tblDichVuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDichVuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblDichVuMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnToListDichVu;
    private javax.swing.JButton btnToListVoucher1;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboTinhTrangLH;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblDichVu;
    private javax.swing.JTable tblDichVuAdded;
    private javax.swing.JTable tblVoucher;
    private javax.swing.JTable tblVoucherAdded;
    private javax.swing.JTextField txtMaLienHe;
    // End of variables declaration//GEN-END:variables
}
