/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package chamsockh;

import chamsockh.DichVu.frmDichVu;
import chamsockh.KhachHang.frmKhachHang;
import chamsockh.KhieuNai.frmHienThiKhieuNai;
import chamsockh.KhieuNai.frmThucHienKhieuNai;
import chamsockh.LienHe.frmLienHe;
import chamsockh.LienHe.frmThucHienLH;
import chamsockh.Voucher.frmVoucher;
import chamsockh.NhanVien.frmNhanVien;
import chamsockh.SanPham.frmSanPham;

/**
 *
 * @author MINH HOANG
 */
public class frmTrangChu extends javax.swing.JFrame {

    /**
     * Creates new form frmTrangChu
     */
    public frmTrangChu() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        desktop = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        mnuDichVu = new javax.swing.JMenu();
        mnuAllDichVu = new javax.swing.JMenuItem();
        mnuVoucher = new javax.swing.JMenu();
        mnuHienThiVoucher = new javax.swing.JMenuItem();
        mnuSanPham = new javax.swing.JMenu();
        mnuAllSanPham = new javax.swing.JMenuItem();
        mnuEmp = new javax.swing.JMenu();
        mnuShowEmp = new javax.swing.JMenuItem();
        mnuLienHe = new javax.swing.JMenu();
        mnuHienThiLH = new javax.swing.JMenuItem();
        btnThucHienLH = new javax.swing.JMenuItem();
        mnuKhachHang = new javax.swing.JMenu();
        mnuShowCus = new javax.swing.JMenuItem();
        mnuKhieuNai = new javax.swing.JMenu();
        mnuTHKN = new javax.swing.JMenuItem();
        mnuHTKN = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("File");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 826, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        getContentPane().add(desktop, java.awt.BorderLayout.CENTER);

        mnuDichVu.setText("Dịch vụ");

        mnuAllDichVu.setText("Hiển thị dịch vụ");
        mnuAllDichVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAllDichVuActionPerformed(evt);
            }
        });
        mnuDichVu.add(mnuAllDichVu);

        menuBar.add(mnuDichVu);

        mnuVoucher.setText("Voucher");

        mnuHienThiVoucher.setText("Hiển thị voucher");
        mnuHienThiVoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuHienThiVoucherActionPerformed(evt);
            }
        });
        mnuVoucher.add(mnuHienThiVoucher);

        menuBar.add(mnuVoucher);

        mnuSanPham.setText("Sản phẩm");

        mnuAllSanPham.setText("Hiển thị sản phẩm");
        mnuAllSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAllSanPhamActionPerformed(evt);
            }
        });
        mnuSanPham.add(mnuAllSanPham);

        menuBar.add(mnuSanPham);

        mnuEmp.setText("Nhân Viên");

        mnuShowEmp.setText("Hiển thị nhân viên");
        mnuShowEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuShowEmpActionPerformed(evt);
            }
        });
        mnuEmp.add(mnuShowEmp);

        menuBar.add(mnuEmp);

        mnuLienHe.setText("Liên hệ");
        mnuLienHe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLienHeActionPerformed(evt);
            }
        });

        mnuHienThiLH.setText("Hiển thị liên hệ");
        mnuHienThiLH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuHienThiLHActionPerformed(evt);
            }
        });
        mnuLienHe.add(mnuHienThiLH);

        btnThucHienLH.setText("Thực hiện liên hệ");
        btnThucHienLH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThucHienLHActionPerformed(evt);
            }
        });
        mnuLienHe.add(btnThucHienLH);

        menuBar.add(mnuLienHe);

        mnuKhachHang.setText("Khách hàng");

        mnuShowCus.setText("Hiển thị khách hàng");
        mnuShowCus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuShowCusActionPerformed(evt);
            }
        });
        mnuKhachHang.add(mnuShowCus);

        menuBar.add(mnuKhachHang);

        mnuKhieuNai.setText("Khiếu nại");

        mnuTHKN.setText("Thực hiện khiếu nại");
        mnuTHKN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTHKNActionPerformed(evt);
            }
        });
        mnuKhieuNai.add(mnuTHKN);

        mnuHTKN.setText("Hiển thị khiếu nại");
        mnuHTKN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuHTKNActionPerformed(evt);
            }
        });
        mnuKhieuNai.add(mnuHTKN);

        menuBar.add(mnuKhieuNai);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuHienThiVoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuHienThiVoucherActionPerformed
        frmVoucher frm = new frmVoucher();
        frm.setSize(910, 550);
        this.desktop.add(frm);
        frm.toFront();
        frm.show();
    }//GEN-LAST:event_mnuHienThiVoucherActionPerformed

    private void mnuAllDichVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAllDichVuActionPerformed
        frmDichVu frm = new frmDichVu();
        frm.setSize(910, 550);
        this.desktop.add(frm);
        frm.toFront();
        frm.show();
    }//GEN-LAST:event_mnuAllDichVuActionPerformed

    private void mnuShowEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuShowEmpActionPerformed
        frmNhanVien frm = new frmNhanVien();
        frm.setSize(910, 550);
        this.desktop.add(frm);
        frm.toFront();
        frm.show();
    }//GEN-LAST:event_mnuShowEmpActionPerformed

    private void mnuAllSanPhamActionPerformed(java.awt.event.ActionEvent evt) {                                              

        frmSanPham frm = new frmSanPham();
        frm.setSize(910, 550);
        this.desktop.add(frm);
        frm.toFront();
        frm.show();
    }             
    
    private void mnuLienHeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLienHeActionPerformed
        frmLienHe frm = new frmLienHe();
        frm.setSize(1386, 646);
        this.desktop.add(frm);
        frm.toFront();
        frm.show();
    }//GEN-LAST:event_mnuLienHeActionPerformed

    private void mnuHienThiLHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuHienThiLHActionPerformed
        frmLienHe frm = new frmLienHe();
        frm.setSize(1386, 646);
        this.desktop.add(frm);
        frm.toFront();
        frm.show();
    }//GEN-LAST:event_mnuHienThiLHActionPerformed

    private void btnThucHienLHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThucHienLHActionPerformed
        frmThucHienLH  frm = new frmThucHienLH();
        frm.setSize(1386, 646);
        this.desktop.add(frm);
        frm.toFront();
        frm.show();
    }//GEN-LAST:event_btnThucHienLHActionPerformed

    private void mnuShowCusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuShowCusActionPerformed
        frmKhachHang frm = new frmKhachHang();
        frm.setSize(910, 550);
        this.desktop.add(frm);
        frm.toFront();
        frm.show();
    }//GEN-LAST:event_mnuShowCusActionPerformed

    private void mnuTHKNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTHKNActionPerformed
        frmThucHienKhieuNai frm = new frmThucHienKhieuNai();
        frm.setSize(910, 550);
        this.desktop.add(frm);
        frm.toFront();
        frm.show();
    }//GEN-LAST:event_mnuTHKNActionPerformed

    private void mnuHTKNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuHTKNActionPerformed
        frmHienThiKhieuNai frm = new frmHienThiKhieuNai();
        frm.setSize(910, 550);
        this.desktop.add(frm);
        frm.toFront();
        frm.show();
    }//GEN-LAST:event_mnuHTKNActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTrangChu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnThucHienLH;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mnuAllDichVu;
    private javax.swing.JMenuItem mnuAllSanPham;
    private javax.swing.JMenu mnuDichVu;
    private javax.swing.JMenu mnuEmp;
    private javax.swing.JMenuItem mnuHTKN;
    private javax.swing.JMenuItem mnuHienThiLH;
    private javax.swing.JMenuItem mnuHienThiVoucher;
    private javax.swing.JMenu mnuKhachHang;
    private javax.swing.JMenu mnuKhieuNai;
    private javax.swing.JMenu mnuLienHe;
    private javax.swing.JMenu mnuSanPham;
    private javax.swing.JMenuItem mnuShowCus;
    private javax.swing.JMenuItem mnuShowEmp;
    private javax.swing.JMenuItem mnuTHKN;
    private javax.swing.JMenu mnuVoucher;
    // End of variables declaration//GEN-END:variables
}
