/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package chamsockh.DichVu;

import BLL.DichVuBll;
import BLL.LienHeBLL;
import chamsockh.ComboBoxItem;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MINH HOANG
 */
public class frmSuaDichVu extends javax.swing.JInternalFrame {

    LienHeBLL lienHeBll = new LienHeBLL();
    DichVuBll dichVuBll = new DichVuBll();
    
    /**
     * Creates new form frmSuaDichVu
     */
    public frmSuaDichVu() {
        initComponents();
        loadDataLienHe();
    }
    
    public void loadDataLienHe(){
//        cboLienHe.removeAllItems();
//        try {
//            ArrayList<String> dsLH = lienHeBll.getAllMaLH();
//            DefaultComboBoxModel model = new DefaultComboBoxModel();
//            for(String a : dsLH){
//                model.addElement(new ComboBoxItem(a, a));
//            }
//            cboLienHe.setModel(model);
//        } catch(Exception e) {
//        }
    }
    
    //public int findIndexInCombobox(String value){
//        int index = -1;
//        for(int i = 0 ; i < cboLienHe.getItemCount() ; i++){
//            if(value.equals(String.valueOf(cboLienHe.getItemAt(i)))){
//                return i;
//            }
//        }
//        return index;
    //}
    
    public void loadDataByMaDV(String madv){
        ResultSet rs = dichVuBll.getAllDichVuByMaDv(madv);
        if(rs != null){
            try {
                while(rs.next()){
                    Vector<String> info = new Vector<String>();
                    txtMaDV.setText(rs.getString("MaDV"));
                    txtTenDV.setText(rs.getString("TenDV"));
                    txtMoTa.setText(rs.getString("MoTaDV"));
                    txtGiaDV.setText(rs.getString("GiaDV"));
                    
//                    int kq = findIndexInCombobox(rs.getString("MaLH"));
//                    cboLienHe.setSelectedIndex(kq);
                }   
            } catch (SQLException ex) {
                Logger.getLogger(frmDichVu.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Không tồn tại mã dịch vụ cần tìm");
        }
    }

    public void loadDataByTenDV(String tendv){
        ResultSet rs = dichVuBll.getAllDichVuByTenDV(tendv);
        if(rs != null){
            try {
                while(rs.next()){
                    Vector<String> info = new Vector<String>();
                    txtMaDV.setText(rs.getString("MaDV"));
                    txtTenDV.setText(rs.getString("TenDV"));
                    txtMoTa.setText(rs.getString("MoTaDV"));
                    txtGiaDV.setText(rs.getString("GiaDV"));
                }   
            } catch (SQLException ex) {
                Logger.getLogger(frmDichVu.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Không tồn tại mã dịch vụ cần tìm");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtMaDV = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTenDV = new javax.swing.JTextField();
        txtGiaDV = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMoTa = new javax.swing.JTextArea();
        btnSuaDichVu = new javax.swing.JButton();
        btnTimDichVu = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Sửa dịch vụ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 20, -1, -1));

        jLabel1.setText("Mã dịch vụ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 61, -1, -1));
        getContentPane().add(txtMaDV, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 250, -1));

        jLabel3.setText("Tên dịch vụ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));
        getContentPane().add(txtTenDV, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 250, -1));
        getContentPane().add(txtGiaDV, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 250, -1));

        jLabel6.setText("Giá dịch vụ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, -1, -1));

        jLabel7.setText("Mô tả");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, -1, -1));

        txtMoTa.setColumns(20);
        txtMoTa.setRows(5);
        jScrollPane2.setViewportView(txtMoTa);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 250, -1));

        btnSuaDichVu.setText("Sửa dịch vụ");
        btnSuaDichVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaDichVuActionPerformed(evt);
            }
        });
        getContentPane().add(btnSuaDichVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, -1, -1));

        btnTimDichVu.setText("Tìm dịch vụ");
        btnTimDichVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimDichVuActionPerformed(evt);
            }
        });
        getContentPane().add(btnTimDichVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuaDichVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaDichVuActionPerformed
        String madv = txtMaDV.getText();
        String tendv = txtTenDV.getText();
        Long giadv = Long.parseLong("0");
        String motadv = txtMoTa.getText();

        try{
            giadv = Long.parseLong(txtGiaDV.getText());
            if(madv.isEmpty() || tendv.isEmpty() || motadv.isEmpty()){
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin để thêm dịch vụ");
            } else {
                int sl = dichVuBll.getSLDichVuTheoMa(madv);
                if(sl > 0){
                    int kq = dichVuBll.update(madv, tendv, giadv, motadv);
                    JOptionPane.showMessageDialog(this, "Sửa dịch vụ thành công");
                } else {
                    JOptionPane.showMessageDialog(this, "Lỗi không thể sửa dịch vụ");
                }
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "Lỗi không thể sửa dịch vụ");
        }
    }//GEN-LAST:event_btnSuaDichVuActionPerformed

    private void btnTimDichVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimDichVuActionPerformed
        String madv = txtMaDV.getText();
        String tendv = txtTenDV.getText();
        
        if(madv.isEmpty() && tendv.isEmpty()){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập thông tin để tìm dịch vụ");
        } else {
            if(madv.isEmpty() == false){
                loadDataByMaDV(madv);
            } else {
                loadDataByTenDV(tendv);
            }
        }
    }//GEN-LAST:event_btnTimDichVuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSuaDichVu;
    private javax.swing.JButton btnTimDichVu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtGiaDV;
    private javax.swing.JTextField txtMaDV;
    private javax.swing.JTextArea txtMoTa;
    private javax.swing.JTextField txtTenDV;
    // End of variables declaration//GEN-END:variables
}
