/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package chamsockh.DichVu;

import chamsockh.ComboBoxItem;
import BLL.DichVuBll;
import BLL.LienHeBLL;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author MINH HOANG
 */
public class frmThemDichVu extends javax.swing.JInternalFrame {

    LienHeBLL lienHeBll = new LienHeBLL();
    DichVuBll dichVuBll = new DichVuBll();
    
    /**
     * Creates new form frmThemDichVu
     */
    public frmThemDichVu() {
        initComponents();
        //loadDataLienHe();
    }
    
//    public void loadDataLienHe(){
//        cboLienHe.removeAllItems();
//        try {
//            ArrayList<String> dsLH = lienHeBll.getAllMaLH();
//            DefaultComboBoxModel model = new DefaultComboBoxModel();
//            for(String a : dsLH){
//                model.addElement(new ComboBoxItem(a, a));
//            }
//            cboLienHe.setModel(model);
//        } catch(Exception e) {
//        }
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtMaDV = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTenDV = new javax.swing.JTextField();
        txtGiaDV = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMoTa = new javax.swing.JTextArea();
        btnThemDichVu = new javax.swing.JButton();

        setBorder(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Thêm dịch vụ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 20, -1, -1));

        jLabel1.setText("Mã dịch vụ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 61, -1, -1));
        getContentPane().add(txtMaDV, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 250, -1));

        jLabel3.setText("Tên dịch vụ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, -1, -1));
        getContentPane().add(txtTenDV, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 250, -1));
        getContentPane().add(txtGiaDV, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 250, -1));

        jLabel6.setText("Giá dịch vụ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel7.setText("Mô tả");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, -1, -1));

        txtMoTa.setColumns(20);
        txtMoTa.setRows(5);
        jScrollPane2.setViewportView(txtMoTa);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 250, -1));

        btnThemDichVu.setText("Tạo dịch vụ");
        btnThemDichVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemDichVuActionPerformed(evt);
            }
        });
        getContentPane().add(btnThemDichVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemDichVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemDichVuActionPerformed
        String madv = txtMaDV.getText();
        String tendv = txtTenDV.getText();
        Long giadv = Long.parseLong("0");
        String motadv = txtMoTa.getText();
        //String lienhe = ((ComboBoxItem)cboLienHe.getSelectedItem()).getKeyString();
        
        try{
            giadv = Long.parseLong(txtGiaDV.getText());
            if(madv.isEmpty() || tendv.isEmpty() || motadv.isEmpty()){
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin để thêm dịch vụ");
            } else {
                int sl = dichVuBll.getSLDichVuTheoMa(madv);
                if(sl == 0){
                    int kq = dichVuBll.insertNew(madv, tendv, giadv, motadv);
                    JOptionPane.showMessageDialog(this, "Thêm dịch vụ thành công");
                } else if(sl > 0) {
                    JOptionPane.showMessageDialog(this, "Lỗi trùng khóa mã dịch vụ");
                } else {
                    JOptionPane.showMessageDialog(this, "Lỗi không thể thêm mới dịch vụ");
                }
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "Lỗi không thể thêm mới dịch vụ");
        }
    }//GEN-LAST:event_btnThemDichVuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThemDichVu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtGiaDV;
    private javax.swing.JTextField txtMaDV;
    private javax.swing.JTextArea txtMoTa;
    private javax.swing.JTextField txtTenDV;
    // End of variables declaration//GEN-END:variables
}
